import './globals.css'
import { Poppins, Jost, JosefinSans } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import MobileNav from '@/components/Navbar/MobileNav'
import MessageButton from '@/components/FloatingButtons/MessageButton'
import MediumNav from '@/components/Navbar/MediumNav'
import Head from 'next/head'
import Notice from '@/components/Notice/Notice'


const poppins = Poppins({ subsets: ['latin'], weight: ['100', '200', '300', '400'] })
const jost = Jost({ subsets: ["cyrillic"], weight: ['100', '200', '300'], variable: "--font-jost" })


export const metadata = {
  title: 'Aesop | Formulations for skin',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jost.variable}`}>
      <Head>
        <meta charSet="utf-8" />
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body className={`${poppins.className} font-zapf text-white bg-primary w-full`}>
        <Notice />
        <div className='hidden xl:flex'>
          <Navbar />
        </div>
        <div className='hidden lg:flex xl:hidden'>
          <MediumNav />
        </div>
        <div className='lg:hidden'>
          <MobileNav />
        </div>
        {children}
        <Footer />
        {/* <MessageButton /> */}
      </body>
    </html>
  )
}